weights: runs/train/exp6/weights/best.pt
cfg: /home/suhao/yolov5/models/yolo-fastest-xl.yaml
data: data/mydata_voc.yaml
hyp: data/hyps/hyp.VOC.yaml
epochs: 300
batch_size: 64
imgsz: 320
half: false
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: 0,1
multi_scale: false
single_cls: false
optimizer: Adam
sync_bn: true
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp7
